apiVersion: apps/v1 
kind: Deployment
metadata:
  name:  test-dev
  namespace: binance-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dev
  template:
    metadata:
      labels:
        app: test-dev
    spec:
      containers:
      - name: app
        image: 10.152.183.174:5000/wbslisten_base:v0.2
        command: ["/bin/sh", "-c"]
        args:
         - wget http://10.152.183.209:9000/repo/binance/test/helm-test.py;
           wget http://10.152.183.209:9000/repo/binance/test/schema.txt;
           wget http://10.152.183.209:9000/repo/binance/test/s3_params.txt;
           python helm-test.py;
